### ISSUE TITLE
Create content for 'About' section

### ISSUE THREAD

**Issue by StuartFeldt** [StuartFeldt/Hashtags#33]
Doesn't even have to be titled 'About' or even need to be there, I just think it looks good.

**Comment by StuartFeldt** [comment]
What should go in this section?
![screen shot 2014-04-14 at 1 42 58 pm](https://cloud.githubusercontent.com/assets/427126/2699262/9f17b202-c404-11e3-937d-2493f4652a75.png)

**Comment by a1exis** [comment]
we should have something here but definitely not 'about.' that's lame and boring an un-advertisingy. As we flush out the actual site and our strategy more, i'll come up with something.

**Comment by StuartFeldt** [comment]
ok, I removed all that stuff, but it seemed empty, so I added some helper text hover over things to fill the space.  It's only in dev right now, http://dev.hashtagmyevent.com/create/standard

![create](https://cloud.githubusercontent.com/assets/427126/2757227/90352f98-c982-11e3-8ead-7e14d14cfc15.jpg)
